name: Java CI

on: push

jobs:
  build:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/checkout@v3

      - name: Run java
        uses: github/setup-java@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
